Made home button on action bar
AJT-Android-Junior-Team/AJT_ANDROID_VERSION_APP pull request #3
Opened 2021-09-16 15:24 UTC by ncliff-git

Сделал кнопку возврата к списку

2021-09-16 19:36 UTC, ncliff-git commented
Убрал backStack, исправил ошибку с fragment recreation

2021-09-20 10:54 UTC, llama-0 commented on app/src/main/java/com/ajt/android_version_app/DetailsFragment.kt
> +    private val binding get() = _binding!!
почему решил убрать обработку ошибки?

2021-09-20 11:15 UTC, llama-0 requested changes
Думаю, что пришло время общие советы оформить в гист какой-нибудь

Я это сделаю и скину в дикорд ссыль.

2021-09-20 11:15 UTC, llama-0 commented on app/src/main/res/values/strings.xml
> +    <string name="exit_message">Complete the application ?</string>
Complete the application -> Do you want to exit?
`Complete` в таких случаях вроде не используется.

2021-09-20 11:15 UTC, llama-0 commented on app/src/main/java/com/ajt/android_version_app/MainActivity.kt
> +        private const val EMPTY_FRAGMENT = -1
Вот это выглядит как костыль. Как я поняла, ты присвоил коды для фрагментов, чтобы с их помощью устроить навигацию. Представь, что у тебя 20 фрагментов.

Попробуй переписать навигацию, проверяя backstack фрагментов на заполненность или перейди на использование NavigationComponent из Android Architecture Components.

После этого ещё раз посмотрю.

2021-09-20 12:23 UTC, ncliff-git commented on app/src/main/java/com/ajt/android_version_app/DetailsFragment.kt
> +    private val binding get() = _binding!!
Сделал как представлено в документации, в любом случае он бы упал в рантайме.

2021-09-20 12:24 UTC, merged

2021-09-21 16:50 UTC, ncliff-git commented on app/src/main/java/com/ajt/android_version_app/MainActivity.kt
> +        private const val EMPTY_FRAGMENT = -1
Почитаю про Navigation Component. Через backstack уже пытался, но там проблема при пересоздании (поворот экрана)